export default [
  {
    id: 1,
    name: 'sad',
    img: require('../../assets/Images/1.jpg'),
    likes: '227,632 likes . 3h 18min',
    Preview:
      'Ashe Moral of the Story . Lana Del Rey Candy Necklace (feat.Jon Batiste) . Angus & Julia Stone Big Jet Plane . Birdy Skinny Love . Jasmine Thompson Mad World . and more',
    img2: require('../../assets/Images/27.jpg'),
    img2Text: 'Sad vibes',
    img2Details: 'Nurse your emotional wounds with these heartbreak tracks.',
    img3: require('../../assets/Images/28.jpg'),
    img3Text: 'Alone Again',
    img3Details:
      'Being alone (again) can be tough, but these songs will keep you company.',
    img4: require('../../assets/Images/4.jpg'),
    img4Text: 'Piano Ballads',
    img4Details: 'Vocals and keys, front and center. Cover',
    img5: require('../../assets/Images/5.jpg'),
    img5Text: 'Comfort Zone',
    img5Details: 'Chilled songs that you are familiar with - no surprises!',
  },
  {
    id: 2,
    name: 'Broken Heart',
    img: require('../../assets/Images/6.jpg'),
    likes: '3.414,478 likes . 6h 18min',
    Preview:
      'Tom Odell Another Love . The Cinematic Orchestra To Build A Home . Lizzy McAlphine ceilings . Sam Smith Make it To Me . Sia Helium . Jodaline High Hopes . and more',
    img2: require('../../assets/Images/2.jpg'),
    img2Text: 'Life Sucks',
    img2Details: 'Having a bad day? We know how it feels!',
    img3: require('../../assets/Images/3.jpg'),
    img3Text: 'Alone Again',
    img3Details:
      'Being alone (again) can be tough, but these songs will keep you company.',
    img4: require('../../assets/Images/4.jpg'),
    img4Text: 'Piano Ballads',
    img4Details: 'Vocals and keys, front and center. Cover',
    img5: require('../../assets/Images/5.jpg'),
    img5Text: 'Comfort Zone',
    img5Details: 'Chilled songs that you are familiar with - no surprises!',
  },
  {
    id: 3,
    name: 'Study Music Lofi 2023!',
    img: require('../../assets/Images/7.jpg'),
    likes: '66,123 likes . 3h 50min',
    Preview:
      'Lofi Waiter The Girl With Tthe Cappuccino . Dontcry Maki . a girl and a cat rainbow bridge . drkmnd Satellite Nights . Dontcry Sashimi . and more',
    img2: require('../../assets/Images/8.jpg'),
    img2Text: 'Lofi Hip-Hop',
    img2Details: 'Lofi crispiest beatmakers. Cover: Cookin Soul',
    img3: require('../../assets/Images/9.jpg'),
    img3Text: 'Lofi covers',
    img3Details:
      'A fresh lofi spin on your favourite tunes and old songs you love.',
    img4: require('../../assets/Images/10.jpg'),
    img4Text: 'Lofi Beats: Best of 2022',
    img4Details:
      'Our editors pick of the best Lofi tunes this year. Study, relax, see you in 2023.',
    img5: require('../../assets/Images/11.jpg'),
    img5Text: 'Coding Mode',
    img5Details: 'Dedicated to all the programmers out there.',
  },
  {
    id: 4,
    name: 'phonk',
    img: require('../../assets/Images/12.jpg'),
    likes: '5.066,523 likes . 3h 47min',
    Preview:
      'MTM Drive Fast . ZODIVK Devil Eyes . KUTE AVOID ME . KSLV Noh Disaster . SHADXWBXRN DAMAGE . GRAVECHILL Twilight . and more',
    img2: require('../../assets/Images/16.jpg'),
    img2Text: 'Top Gaming Tracks',
    img2Details: 'Top Gaming Tracks is one of ',
    img3: require('../../assets/Images/13.jpg'),
    img3Text: 'ULTRA GAMING',
    img3Details: 'Dance, bass, EDM, trap,phonk: the perfect gaming mix.',
    img4: require('../../assets/Images/14.jpg'),
    img4Text: 'Internet People',
    img4Details: 'The soundtrack to the internet. Cover: BLP KOSHER',
    img5: require('../../assets/Images/15.jpg'),
    img5Text: 'Sped up songs',
    img5Details: '150%',
  },
  {
    id: 5,
    name: 'Country Mix',
    img: require('../../assets/Images/17.jpg'),
    likes: '2.066,523 likes . 2h 53min',
    Preview:
      'Rascal Flatts Won"t Let Go . Cole Swindell You Should Be Here . Morgan Wallen Bandaid On A Bullet Hole . Kane Brown Heaven . and more',
    img2: require('../../assets/Images/18.jpg'),
    img2Text: 'Chillin on a Dirt Road',
    img2Details: 'Country music to get you back to the basics.',
    img3: require('../../assets/Images/19.jpg'),
    img3Text: 'Country Gold',
    img3Details: 'Spotify country fan favorite. Artist: Lady A',
    img4: require('../../assets/Images/20.jpg'),
    img4Text: 'Country Kind of Love',
    img4Details: 'Nothing but beautful country love songs.',
    img5: require('../../assets/Images/21.jpg'),
    img5Text: 'Country Top 50',
    img5Details:
      'Country music 50 most played songs in the world. Updated weekly. Cover: Morgan Wallen',
  },
  {
    id: 6,
    name: 'pop music for studying',
    img: require('../../assets/Images/22.jpg'),
    likes: '970,523 likes . 3h 28min',
    Preview:
      'Imagine Dragons Whatever it Takes . Glass Animals Heat Waves . Marsmello Silence . Marshmello FRIENDS . The Score Unstoppable . and more',
    img2: require('../../assets/Images/23.jpg'),
    img2Text: 'Pop Rising',
    img2Details: 'Who"s now and next in pop. Cover: Labrinth & Billie Elish',
    img3: require('../../assets/Images/24.jpg'),
    img3Text: 'teen beats',
    img3Details: 'we didn"t have CharBrine on our 2023 bingo card tbh',
    img4: require('../../assets/Images/25.jpg'),
    img4Text: 'Pop Sauce',
    img4Details: 'next gen pop Cover: Lauren Spencer Smith, GAYLE 1 Em Beihold',
    img5: require('../../assets/Images/26.jpg'),
    img5Text: 'just hits',
    img5Details:
      'Current Favorites and exciting new music. Cover: David Guetta, Anne-Marie',
  },
];
